### PR TITLE
IPED a Brazilian tool for forensic

### PR DESCRIPTION
**Pull request by jandersoncampelo**

### CODE REVIEW

**Comment by cugu** [comment]
Thanks for the contribution. Is there an English web page about this tool somewhere?

**Comment by jandersoncampelo** [comment]
> Thanks for the contribution. Is there an English web page about this tool somewhere?

Unfortunately not yet, but I'm starting a blog I'll put on my to-do list.

**Comment by cugu** [comment]
They released it on GitHub an are changing the language to English. Nice! Thanks for the advice.

**Comment by jandersoncampelo** [comment]
Awesome!

**Pull request merged**
